[workspace]
resolver = "2"

members = [
    "crates/*",
]

# Remove debug from the exe for faster compile times
# https://corrode.dev/blog/tips-for-faster-rust-compile-times/#turn-off-debuginfo
[profile.dev]
debug = 0
strip = "debuginfo"