apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: workspace
build:
  artifacts:
  - image: purton/web-server
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - deployment.yaml
