[package]
name = "realtime"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }
tokio-postgres = "0.7"
futures = "0.3"
axum = { version="0.7", features = ["ws"] }
futures-channel = "0.3"
