version: '3.4'
services:

  development:
    build: 
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ..:/workspace:cached
      - target:/workspace/target # Set target as a volume for performance. 
    environment:
      DATABASE_URL: postgresql://postgres:testpassword@db:5432/postgres?sslmode=disable

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    working_dir: /workspace

volumes:
  target:
  node_modules:
